-- Create Database
CREATE DATABASE ECOMMERCE_SALES;

-- Use Database
USE ECOMMERCE_SALES;

-- Create Table
CREATE TABLE SUPERSTORE (
	SHIP_MODE VARCHAR(50),
	SEGMENT VARCHAR(50),
	COUNTRY VARCHAR(50),
	CITY VARCHAR(100),
	STATE VARCHAR(100),
	POSTAL_CODE INT,
	REGION VARCHAR(50),
	CATEGORY VARCHAR(50),
	SUB_CATEGORY VARCHAR(50),
	SALES DECIMAL(10, 2),
	QUANTITY INT,
	DISCOUNT DECIMAL(4, 2),
	PROFIT DECIMAL(10, 2)
);

-- Select Table
SELECT * FROM SUPERSTORE;